lindb/linsight

web/src/features/dashboard/components/VariableList.tsx
web/src/features/dashboard/components/variables.scss
web/src/pages/EditDashboard.tsx
web/src/stores/dashboard.store.ts
web/yarn.lock

[feat]: variable list can re-order

---

web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/Setting.tsx
web/src/stores/dashboard.store.ts

[refactor]: set dashboard uid to url when create dashboard successfull

---

accesscontrol/policy.go
cmd/main.go
cmd/migrator.go
http/api/chart.go
http/api/chart_test.go
http/api/dashboard_test.go
http/deps/api.go
http/router.go
model/chart.go
service/chart.go
service/chart_test.go
service/dashboard.go
web/src/constants/api.ts
web/src/features/chart/index.tsx
web/src/features/chart/module.ts
web/src/features/dashboard/ListDashboard.tsx
web/src/services/chart.service.ts
web/src/services/datasource.service.ts
web/src/services/index.ts
web/src/services/metric.service.ts
web/src/services/platform.service.ts
web/src/types/chart.ts
web/src/types/index.ts

[feat]: search chart repo

---

.github/workflows/linsight.yml
README.md

[ci]: add codecov

---

web/src/components/common/SimpleStatusTip.tsx
web/src/components/common/StatusTip.tsx
web/src/components/dashboard/Panel.tsx
web/src/contexts/PlatformContextProvider.tsx
web/src/features/chart/index.tsx
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/ListDashboard.tsx
web/src/features/explore/module.ts
web/src/features/observe/DynamicDashboard.tsx
web/src/features/observe/module.ts
web/src/features/setting/datasource/EditDataSource.tsx
web/src/features/setting/datasource/ListDataSource.tsx
web/src/features/setting/datasource/NewDataSource.tsx
web/src/features/setting/module.ts
web/src/hooks/index.ts
web/src/hooks/use.metric.ts
web/src/hooks/use.request.ts
web/src/hooks/use.ui.ts
web/src/hooks/use.url.ts

[feat]: useQuery wrap

---

web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/PanelSetting.tsx
web/src/plugins/datasources/lindb/module.ts
web/src/plugins/visualizations/gauge/module.ts
web/src/plugins/visualizations/list/module.ts
web/src/plugins/visualizations/pie/module.ts
web/src/plugins/visualizations/table/module.ts
web/src/plugins/visualizations/text/module.ts
web/src/plugins/visualizations/timeseries/module.ts
web/src/stores/datasource.store.ts
web/src/types/datasource.ts
web/src/types/theme.ts
web/src/types/visualization.ts

[feat]: add datasource category(visualization)

---

go.mod
go.sum
plugin/datasource/lindb/client.go
plugin/datasource/lindb/data_query.go
plugin/datasource/lindb/data_query_test.go
plugin/datasource/lindb/model.go
web/src/App.tsx
web/src/hooks/use.metric.ts
web/src/images/logo-dark.svg
web/src/images/logo.svg
web/src/plugins/datasources/lindb/Datasource.ts
web/src/styles/layout.scss
web/src/types/datasource.ts

[feat]: time picker/query time range

---

plugin/datasource/lindb/metadata_query.go
plugin/datasource/lindb/model.go
web/src/App.tsx
web/src/components/input/LinSelect.tsx
web/src/hooks/use.variable.ts
web/src/plugins/datasources/lindb/Datasource.ts
web/src/plugins/datasources/lindb/VariableEditor.tsx
web/src/plugins/datasources/lindb/components/TagKeySelect.tsx

[feat]: tag value variable

---

README.md

[chore]: features desc in README

---

README.md
plugin/datasource/lindb/data_query.go
plugin/datasource/lindb/model.go
web/package.json
web/src/contexts/VariableContextProvider.tsx
web/src/features/dashboard/View.tsx
web/src/hooks/use.metric.ts
web/src/plugins/datasources/lindb/Datasource.ts
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/plugins/datasources/lindb/components/FieldSelect.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/plugins/datasources/lindb/types.ts
web/src/utils/template.ts
web/yarn.lock

[chore]: metric query condition can use variable

---

web/src/plugins/formats/misc/percent.ts
web/src/plugins/visualizations/text/OptionsEditor.tsx
web/src/plugins/visualizations/text/Text.tsx
web/src/plugins/visualizations/timeseries/TimeSeries.tsx
web/src/types/format.ts
web/src/utils/dataset.ts

[feat]: text stats visualizations

---

web/package.json
web/src/App.tsx
web/src/components/common/Loading.tsx
web/src/components/common/SimpleStatusTip.tsx
web/src/components/common/loading.scss
web/src/components/dashboard/Panel.tsx
web/src/components/explore/MetricExplore.tsx
web/src/components/explore/metric-explore.scss
web/src/components/index.ts
web/src/components/input/LinSelect.tsx
web/src/contexts/PlatformContextProvider.tsx
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/dashboard.scss
web/src/features/explore/Explore.tsx
web/src/features/explore/explore.scss
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/plugins/datasources/lindb/VariableEditor.tsx
web/src/plugins/datasources/lindb/components/FieldSelect.tsx
web/src/plugins/datasources/lindb/components/MetricNameSelect.tsx
web/src/plugins/datasources/lindb/components/TagKeySelect.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/plugins/datasources/lindb/query-edit.scss
web/src/styles/index.scss
web/src/types/datasource.ts
web/src/types/format.ts
web/src/utils/object.ts
web/src/utils/template.ts
web/static/index.html

[feat]: metric explore

---

plugin/datasource/lindb/model.go
web/src/hooks/use.metric.ts
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/plugins/datasources/lindb/query-edit.scss

[feat]: where condition editor

---

web/src/components/dashboard/Panel.tsx
web/src/features/dashboard/PanelEditor.tsx
web/src/stores/panel.store.ts

[bug]: fix panel options modify ineffective

---

web/src/components/explore/AddToCharts.tsx
web/src/components/explore/MetricExplore.tsx
web/src/components/index.ts
web/src/features/chart/index.tsx
web/src/features/explore/Explore.tsx

[feat]: metric explore can be saved to chart repository

---

http/api/boot.go
model/boot_data.go
plugin/datasource/lindb/client.go
plugin/datasource/lindb/data_query.go
plugin/datasource/lindb/metadata_query.go
plugin/datasource/lindb/metadata_query_test.go
web/src/App.tsx
web/src/contexts/QueryEditContextProvider.tsx
web/src/features/dashboard/components/VariableEditor.tsx
web/src/features/dashboard/components/ViewVariables.tsx
web/src/features/explore/Explore.tsx
web/src/plugins/datasources/lindb/Datasource.ts
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/plugins/datasources/lindb/VariableEditor.tsx
web/src/plugins/datasources/lindb/components/FieldSelect.tsx
web/src/plugins/datasources/lindb/components/NamespaceSelect.tsx
web/src/plugins/datasources/lindb/components/TagKeySelect.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/styles/layout.scss
web/src/types/platform.ts

- home page
- namespace select
Tests

[feat]: home page/namespace select

---

web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/components/ViewVariables.tsx
web/src/types/dashboard.ts
web/src/utils/variable.ts

[feat]: save variable selected value/init variable values when dashboard render

---

web/src/components/dashboard/AddPanelWidget.tsx
web/src/components/dashboard/Panel.tsx
web/src/constants/dashboard.ts
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/View.tsx
web/src/features/dashboard/components/RowPanel.tsx
web/src/features/dashboard/dashboard.scss
web/src/stores/dashboard.store.ts
web/src/styles/theme/_palette.scss
web/src/utils/object.ts

[feat]: row panel

---

web/src/App.tsx
web/src/styles/layout.scss
web/src/styles/theme/_palette.scss

[refactor]: sider nav style

---

web/src/components/dashboard/AddPanelWidget.tsx
web/src/components/dashboard/Panel.tsx
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/PanelEditor.tsx
web/src/features/dashboard/View.tsx
web/src/features/dashboard/ViewPanel.tsx
web/src/features/dashboard/components/ViewVariables.tsx
web/src/stores/dashboard.store.ts
web/src/types/visualization.ts

[refactor]: panel/grid id

---

web/src/features/dashboard/PanelSetting.tsx
web/src/features/dashboard/dashboard.scss
web/src/plugins/visualizations/gauge/Gauge.tsx
web/src/plugins/visualizations/gauge/OptionsEditor.tsx
web/src/plugins/visualizations/gauge/components/GaugeChart.tsx
web/src/plugins/visualizations/gauge/components/chart.config.ts
web/src/plugins/visualizations/gauge/components/gauge.scss
web/src/plugins/visualizations/gauge/module.ts
web/src/plugins/visualizations/gauge/types.ts
web/src/plugins/visualizations/timeseries/OptionsEditor.tsx
web/src/plugins/visualizations/timeseries/components/TimeSeriesChart.tsx
web/src/types/visualization.ts
web/src/utils/object.ts

[feat]: gauge chart plugin/thresholds

---

http/api/dashboard.go
http/api/dashboard_test.go
model/dashboard.go
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/View.tsx
web/src/features/dashboard/components/VariableEditor.tsx
web/src/features/dashboard/components/VariableList.tsx
web/src/features/dashboard/components/ViewVariables.tsx
web/src/services/dashboard.service.ts
web/src/stores/dashboard.store.ts
web/src/types/dashboard.ts
web/src/types/visualization.ts

[feat]: dashboard config use grafana data modal

---

web/src/components/dashboard/AddPanelWidget.tsx
web/src/contexts/PanelEditContextProvider.tsx
web/src/contexts/PlatformContextProvider.tsx
web/src/features/dashboard/PanelSetting.tsx
web/src/plugins/formats/data/data.ts
web/src/plugins/formats/data/module.ts
web/src/plugins/formats/time/module.ts
web/src/plugins/formats/time/time.ts
web/src/plugins/visualizations/gauge/module.ts
web/src/plugins/visualizations/timeseries/TimeSeries.tsx
web/src/plugins/visualizations/timeseries/components/TimeSeriesChart.tsx
web/src/plugins/visualizations/timeseries/components/chart.config.ts
web/src/plugins/visualizations/timeseries/types.ts
web/src/stores/dashboard.store.ts
web/src/types/format.ts
web/src/types/visualization.ts
web/src/utils/format.ts

[refactor]: format plugin

---

.github/workflows/docker-latest.yml
web/Makefile

Issue Number: None
```
#32 [linux/arm64 web_builder 5/5] RUN make build-frontend
#32 140.1 info There appears to be trouble with your network connection. Retrying...
#32 147.5 info There appears to be trouble with your network connection. Retrying...
#32 165.7 info There appears to be trouble with your network connection. Retrying...
#32 183.8 info There appears to be trouble with your network connection. Retrying...
#32 189.0 info There appears to be trouble with your network connection. Retrying...
#32 195.4 info There appears to be trouble with your network connection. Retrying...
#32 217.7 info There appears to be trouble with your network connection. Retrying...
#32 225.9 info There appears to be trouble with your network connection. Retrying...
#32 243.6 info There …
```

[feat]: CI support arm64

---

web/src/components/dashboard/Panel.tsx
web/src/constants/panel.ts
web/src/features/dashboard/PanelSetting.tsx
web/src/features/dashboard/View.tsx
web/src/plugins/visualizations/gauge/components/GaugeChart.tsx
web/src/plugins/visualizations/gauge/components/chart.config.ts
web/src/plugins/visualizations/gauge/components/gauge.scss
web/src/plugins/visualizations/gauge/module.ts
web/src/plugins/visualizations/stat/Stat.tsx
web/src/plugins/visualizations/stat/module.ts
web/src/types/visualization.ts
web/src/utils/css.ts
web/src/utils/index.ts
web/src/utils/panel/field.ts

[feat]: gauge chart render based on thresholds

---

.github/workflows/docker-latest.yml
Dockerfile-gh

[bug]: fix docker image not include web

---

.github/workflows/dockerhub-description.yml

[feat]: add sync desc to docker hub

---

web/src/components/explore/QueryEditor.tsx
web/src/components/explore/query.editor.scss
web/src/features/dashboard/Dashboard.tsx
web/src/index.tsx
web/src/stores/dashboard.store.ts
web/src/stores/query.editor.store.ts
web/src/types/tracker.ts

[feat]: track dashboard unsaved

---

web/src/components/explore/QueryEditor.tsx
web/src/components/explore/query.editor.scss
web/src/features/dashboard/components/VariableList.tsx
web/src/features/dashboard/dashboard.scss
web/src/index.tsx
web/src/stores/query.editor.store.ts
web/src/utils/dnd.ts
web/src/utils/index.ts

[feat]: query editor support drag

---

web/src/features/dashboard/components/VariableList.tsx
web/src/features/dashboard/components/variables.scss
web/src/index.tsx
web/src/stores/dashboard.store.ts

[refactor]: variable list

---

web/src/components/dashboard/Panel.tsx
web/src/features/dashboard/dashboard.scss
web/src/plugins/visualizations/timeseries/components/timeseries.scss

[bug]: panel menu not show when mouse already in panel container

---

http/api/datasource_query.go
model/query.go
web/src/components/dashboard/Panel.tsx
web/src/components/explore/MetricExplore.tsx
web/src/components/explore/QueryEditor.tsx
web/src/components/explore/query.editor.scss
web/src/contexts/PanelEditContextProvider.tsx
web/src/contexts/QueryEditContextProvider.tsx
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/plugins/datasources/lindb/query-edit.scss
web/src/stores/dashboard.store.ts
web/src/types/datasource.ts
web/src/utils/dataset.ts
web/static/index.html

[feat]: series legend format

---

web/src/components/common/TimePicker.tsx
web/src/components/explore/QueryEditor.tsx
web/src/constants/dashboard.ts
web/src/contexts/VariableContextProvider.tsx
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/components/DashboardSearchModal.tsx
web/src/features/explore/Explore.tsx
web/src/hooks/use.metric.ts
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/types/dashboard.ts

[feat]: refresh dashboard(auto/manual)

---

http/api/chart.go
http/api/chart_test.go
http/router.go
service/chart.go
service/chart_test.go
web/src/features/chart/ChartDetail.tsx
web/src/features/chart/index.tsx
web/src/features/dashboard/components/DashboardSearch.tsx
web/src/services/chart.service.ts

[feat]: delete chart

---

accesscontrol/policy.go
cmd/main.go
cmd/migrator.go
http/api/team.go
http/api/team_test.go
http/router.go
model/org.go
model/team.go
model/user.go
service/chart.go
service/team.go
service/team_test.go

[feat]: team api

---

http/api/boot.go
http/api/org.go
http/api/org_test.go
http/api/team.go
http/router.go
model/org.go
service/org.go
service/org_test.go
web/index.html
web/src/components/layout/FeatureMenu.tsx
web/src/constants/api.ts
web/src/features/setting/Setting.tsx
web/src/features/setting/index.tsx
web/src/features/setting/org/EditOrg.tsx
web/src/features/setting/org/NewOrg.tsx
web/src/features/setting/org/OrgList.tsx
web/src/services/index.ts
web/src/services/org.service.ts
web/src/styles/layout.scss
web/src/types/index.ts
web/src/types/org.ts

[feat]: org setting

---

accesscontrol/policy.go
cmd/main.go
cmd/migrator.go
config/nav.json
embed.go
http/api/nav.go
http/api/nav_test.go
http/router.go
model/boot_data.go
model/nav.go
service/nav.go
service/nav_test.go
service/user.go
web/index.html
web/src/features/setting/Setting.tsx
web/src/features/setting/menu/MenuSetting.tsx
web/src/features/setting/menu/menu.scss
web/src/services/index.ts
web/src/services/nav.service.ts
web/src/styles/icon-fonts/fonts.scss
web/src/styles/index.scss
web/src/types/index.ts
web/src/types/nav.ts

[feat]: nav setting

---

http/api/user.go
http/api/user_test.go
http/router.go
model/user.go
service/user.go
service/user_test.go
web/src/constants/api.ts
web/src/features/user/ChangePassword.tsx
web/src/features/user/Profile.tsx
web/src/services/user.service.ts
web/src/types/user.ts

[feat]: change user password

---

.github/workflows/docker-latest.yml
.github/workflows/frontend.yml
.github/workflows/linsight.yml
README.md
http/api/user.go
http/api/user_test.go
http/router.go
service/user.go
service/user_test.go
web/src/features/setting/user/EditUser.tsx
web/src/services/user.service.ts

[feat]: disable/enable user

---

accesscontrol/policy.go
cmd/main.go
cmd/migrator.go
http/api/org.go
http/api/org_test.go
http/api/user.go
http/api/user_test.go
http/router.go
http/router_test.go
model/user.go
pkg/db/db.go
pkg/util/context_test.go
service/authenticate.go
service/authenticate_test.go
service/org.go
service/org_test.go
service/user.go
service/user_test.go
web/src/constants/api.ts
web/src/features/setting/org/EditOrg.tsx
web/src/features/setting/user/AddOrgModal.tsx
web/src/features/setting/user/EditUser.tsx
web/src/features/setting/user/OrgList.tsx
web/src/services/org.service.ts
web/src/services/user.service.ts
web/src/types/user.ts

[feat]: user org setting

---

http/api/boot.go
http/api/boot_test.go
http/api/user.go
http/api/user_test.go
http/router.go
model/user.go
pkg/db/db_test.go
service/user.go
service/user_test.go
web/src/components/layout/FeatureMenu.tsx
web/src/constants/api.ts
web/src/services/user.service.ts

[feat]: switch org

---

web/src/features/setting/datasource/EditDataSource.tsx
web/src/features/setting/datasource/datasource.scss
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/plugins/datasources/lindb/SettingEditor.tsx
web/src/plugins/datasources/lindb/components/FieldSelect.tsx
web/src/plugins/datasources/lindb/components/MetricNameSelect.tsx
web/src/plugins/datasources/lindb/components/NamespaceSelect.tsx
web/src/plugins/datasources/lindb/components/TagKeySelect.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx

[feat]: lindb datasource can setting namespace

---

model/datasource.go
service/datasource.go
service/datasource_test.go
service/team.go
service/user.go
service/user_test.go
web/src/features/setting/datasource/EditDataSource.tsx
web/src/features/setting/datasource/ListDataSource.tsx
web/src/types/datasource.ts

[feat]: support default datasource

---

plugin/datasource/lindb/data_query.go
plugin/datasource/lindb/data_query_test.go
web/src/contexts/VariableContextProvider.tsx
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/components/VariableEditor.tsx
web/src/features/dashboard/components/ViewVariables.tsx
web/src/hooks/use.variable.ts
web/src/plugins/datasources/lindb/Datasource.ts
web/src/plugins/datasources/lindb/QueryEditor.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/plugins/datasources/lindb/query-edit.scss
web/src/plugins/datasources/lindb/types.ts
web/src/stores/dashboard.store.ts
web/src/utils/template.ts
web/src/utils/variable.ts
web/static/index.html

[feat]: query editor support variable

---

config/components.json
http/api/component.go
http/api/component_test.go
http/router.go
http/router_test.go
model/component.go
service/authorize.go
service/authorize_test.go
service/component.go
service/component_test.go
web/src/features/setting/org/EditOrg.tsx
web/src/features/setting/org/OrgComponent.tsx
web/src/services/component.service.ts
web/src/types/platform.ts

[feat]: org component

---

model/acl.go
model/acl_test.go
model/component.go
service/authorize.go
service/authorize_test.go
service/component.go
service/component_test.go
web/src/features/setting/Setting.tsx
web/src/features/setting/component/ComponentSetting.tsx
web/src/features/setting/component/OrgComponent.tsx
web/src/services/component.service.ts

[feat]: org component role setting

---

config/components.json
web/src/features/setting/Setting.tsx
web/src/features/setting/component/ComponentSetting.tsx
web/src/features/setting/component/OrgComponent.tsx
web/src/features/setting/module.ts
web/src/features/setting/team/EditTeam.tsx
web/src/features/setting/team/TeamList.tsx

[feat]: setting view based on acl

---

http/api/dashboard.go
http/api/dashboard_test.go
http/api/datasource_query.go
http/api/datasource_query_test.go
plugin/datasource/lindb/client.go
plugin/datasource/lindb/client_test.go
plugin/datasource/lindb/data_query.go
plugin/datasource/lindb/data_query_test.go
plugin/datasource/lindb/metadata_query.go
plugin/datasource/lindb/metadata_query_test.go
plugin/datasource/lindb/model.go
plugin/datasource/lindb/model_test.go
plugin/datasource/manager.go
plugin/datasource/manager_test.go
service/authorize.go
web/src/components/input/DatasourceSelectForm.tsx
web/src/plugins/datasources/lindb/components/NamespaceSelect.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx

[feat]: lindb datasource metadata support prefix query

---

pkg/util/strings.go
pkg/util/strings_test.go
plugin/datasource/lindb/metadata_query.go
plugin/datasource/lindb/metadata_query_test.go
plugin/datasource/lindb/model.go
web/src/plugins/datasources/lindb/Datasource.ts
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/plugins/datasources/lindb/types.ts

[feat]: query where input support cascade conditions

---

plugin/datasource/lindb/metadata_query_test.go
web/src/plugins/datasources/lindb/QueryEditor.tsx

[bug]: clear query request when edit query options

---

config/components.json
web/src/features/dashboard/Dashboard.tsx
web/src/hooks/use.variable.ts
web/src/plugins/datasources/lindb/Datasource.ts
web/src/plugins/datasources/lindb/VariableEditor.tsx
web/src/plugins/datasources/lindb/components/WhereEditor.tsx
web/src/types/datasource.ts

[feat]: add where conditions when select lindb tag value variable

---

README.md
web/package.json
web/src/plugins/datasources/lindb/Datasource.ts
web/src/stores/dashboard.store.ts
web/static/index.html
web/yarn.lock

[bug]: fix cannot remove variable from variables

---

web/src/features/dashboard/components/ViewVariables.tsx
web/src/hooks/use.variable.ts
web/src/plugins/datasources/lindb/Datasource.ts
web/src/types/datasource.ts
web/src/utils/template.ts

[feat]: variable cascade select

---

web/src/features/dashboard/components/VariableEditor.tsx
web/src/features/dashboard/components/ViewVariables.tsx
web/src/features/dashboard/components/common/CustomEditor.tsx
web/src/types/dashboard.ts

[feat]: custom type variable

---

web/src/plugins/datasources/lindb/VariableEditor.tsx

[feat]: lindb variable editor support default ns

---

web/index.html
web/src/components/explore/QueryEditor.tsx
web/src/components/explore/query.editor.scss
web/src/components/input/DatasourceSelect.tsx
web/src/components/input/DatasourceSelectForm.tsx
web/src/constants/dashboard.ts
web/src/contexts/PanelEditContextProvider.tsx
web/src/contexts/QueryEditContextProvider.tsx
web/src/contexts/TargetsContextProvider.tsx
web/src/features/dashboard/PanelEditor.tsx
web/src/features/explore/Explore.tsx
web/src/hooks/use.metric.ts
web/src/stores/datasource.store.ts

[feat]: support mixed datasource for query editor

---

web/src/components/dashboard/Panel.tsx
web/src/features/dashboard/View.tsx
web/src/features/dashboard/ViewPanel.tsx

[feat]: panel add menu control

---

cmd/migrator.go
http/api/chart.go
http/api/chart_test.go
http/api/dashboard.go
http/api/dashboard_test.go
http/router.go
http/server.go
http/server_test.go
http/static.go
http/static_test.go
model/chart.go
model/dashboard.go
model/dashboard_test.go
model/link.go
service/chart.go
service/chart_test.go
web/src/components/AddToDashboard.tsx
web/src/components/dashboard/Panel.tsx
web/src/components/explore/AddToCharts.tsx
web/src/features/chart/ChartDetail.tsx
web/src/features/chart/index.tsx
web/src/features/explore/Explore.tsx
web/src/services/chart.service.ts
web/src/stores/dashboard.store.ts
web/src/types/chart.ts
web/src/types/visualization.ts

[feat]: link charts to dashboard

---

http/api/chart.go
http/api/chart_test.go
http/router.go
model/base.go
model/chart.go
model/dashboard.go
service/chart.go
service/chart_test.go
service/dashboard.go
service/dashboard_test.go
web/index.html
web/src/features/chart/ListDashboardByChart.tsx
web/src/features/chart/index.tsx
web/src/services/chart.service.ts

[feat]: list dashboards by chart

---

http/api/chart.go
http/api/chart_test.go
http/router.go
pkg/db/db.go
pkg/db/db_test.go
pkg/db/migrator.go
pkg/db/migrator_test.go
service/chart.go
service/chart_test.go

[feat]: unlink chart from dashboard api

---

web/index.html
web/package.json
web/src/components/dashboard/Panel.tsx
web/src/features/chart/ListDashboardByChart.tsx
web/src/features/chart/index.tsx
web/src/features/dashboard/PanelEditor.tsx
web/src/stores/dashboard.store.ts
web/src/styles/icon-fonts/fonts.scss
web/src/styles/index.scss
web/src/utils/index.ts
web/src/utils/panel/chart.ts
web/static/index.html
web/yarn.lock

[feat]: panel editor support chart link

---

http/api/chart.go
http/api/chart_test.go
http/api/dashboard.go
http/api/dashboard_test.go
model/chart.go
model/integration.go
service/chart.go
service/integration.go
service/integration_test.go

[feat]: integration relate

---

cmd/main.go
cmd/migrator.go
config/server.go
go.mod
go.sum
model/dashboard.go
pkg/fileutil/watch.go
pkg/fileutil/watch_test.go
pkg/uuid/short_uuid_test.go
provisioning/dashboard/file_loader.go
provisioning/dashboard/file_loader_test.go
provisioning/dashboard/loader.go
provisioning/dashboard/loader_test.go
provisioning/dashboard/models.go
provisioning/deps/provisioning.go
provisioning/interface.go
provisioning/service/ProvisionService.go
provisioning/service/ProvisionService_test.go
service/dashboard.go
service/dashboard_test.go

[feat]: find provisioning dashboard from file

---

web/src/components/common/IntegrationIcon.tsx
web/src/contexts/PanelEditContextProvider.tsx
web/src/features/dashboard/PanelSetting.tsx
web/src/services/chart.service.ts

[feat]: unlink chart from dashboard

---

web/src/components/dashboard/panel.scss
web/src/features/dashboard/PanelSetting.tsx

[feat]: link chart to dashboard

---

http/api/dashboard.go
http/api/dashboard_test.go
model/dashboard.go
model/dashboard_test.go
service/dashboard.go
service/dashboard_test.go
web/src/components/dashboard/Panel.tsx
web/src/features/dashboard/Dashboard.tsx
web/src/features/dashboard/View.tsx
web/src/stores/dashboard.store.ts
web/src/types/dashboard.ts

[feat]: provisioning dashboard cannot be edit

---

model/base.go
web/src/features/chart/index.tsx
web/src/features/dashboard/components/DashboardSearch.tsx
web/src/hooks/index.ts
web/src/hooks/use.pagination.ts
web/src/services/dashboard.service.ts
web/src/types/chart.ts
web/src/types/dashboard.ts

[feat]: dashboard/chart table support pagination

---

cmd/main.go
cmd/migrator.go
http/api/chart.go
http/api/chart_test.go
http/api/dashboard.go
http/api/dashboard_test.go
http/api/tag.go
http/api/tag_test.go
http/deps/api.go
http/router.go
model/base.go
model/dashboard.go
model/dashboard_test.go
model/integration.go
model/star.go
service/dashboard.go
service/dashboard_test.go
service/integration.go
service/integration_test.go
service/star.go
service/star_test.go
service/tag.go
service/tag_test.go
web/src/features/dashboard/Setting.tsx
web/src/features/dashboard/components/DashboardSearch.tsx
web/src/stores/dashboard.store.ts
web/src/types/dashboard.ts

[feat]: dashboard support tags

---

web/src/components/index.ts
web/src/components/input/SearchFilterInput.tsx
web/src/components/input/TagSelectInput.tsx
web/src/components/input/tag-select-input.scss
web/src/features/dashboard/Setting.tsx
web/src/features/dashboard/components/DashboardSearch.tsx

[feat]: tag select input

---

model/datasource.go
model/query.go
plugin/datasource.go
plugin/datasource/lindb/client.go
plugin/datasource/lindb/client_test.go
plugin/datasource/lindb/data_query.go
plugin/datasource/lindb/data_query_test.go
plugin/datasource/manager.go
service/dashboard_test.go
service/datasource.go
web/index.html
web/package.json
web/src/components/common/TimePicker.tsx
web/src/constants/dashboard.ts
web/src/features/setting/datasource/EditDataSource.tsx
web/src/features/setting/datasource/ListDataSource.tsx
web/src/features/setting/datasource/datasource.scss
web/src/hooks/use.metric.ts
web/src/types/datasource.ts
web/src/utils/index.ts
web/src/utils/string.ts
web/src/utils/time.ts
web/static/index.html
web/yarn.lock

[feat]: datasource support time zone

---

web/src/features/setting/datasource/EditDataSource.tsx
web/src/features/trace/TraceView.tsx

[bug]: fix time zone cannot select

---

Dockerfile
Dockerfile-gh
web/package.json
web/src/components/explore/QueryEditor.tsx
web/src/features/explore/Explore.tsx
web/src/features/trace/TraceView.tsx
web/yarn.lock

[bug]: explore data error, when no datasource
